"""
=============================================================
CEP - Smart Energy-Harvesting Sensor Node on a Rotating Shaft
Group 9: Faraday's Law & Motional EMF
=============================================================
Physics: Faraday's law, Lenz's law, induced EMF, current, power
Output : 3 plots + CSV data file for integration with Module 10
"""

import numpy as np
import matplotlib.pyplot as plt
import csv

# ─────────────────────────────────────────────
# SECTION 1: PHYSICAL PARAMETERS
# ─────────────────────────────────────────────

N    = 200          # Number of coil turns
B0   = 0.35         # Peak magnetic field from shaft magnet [Tesla]
A    = 0.004        # Coil cross-section area [m^2] = 4 cm x 10 cm coil
R    = 12.0         # Coil resistance [Ohm]
f    = 50.0         # Oscillation frequency of magnet [Hz] = shaft speed equivalent
omega = 2 * np.pi * f   # Angular frequency [rad/s] # ω ≈ 314.16 rad/s

# ─────────────────────────────────────────────
# SECTION 2: TIME ARRAY (3 full cycles)
# ─────────────────────────────────────────────

T_period = 1.0 / f                      # Period of one oscillation [seconds]
t_total  = 3 * T_period                 # Simulate 3 full cycles You want to simulate 3 full rotations of the shaft magnet
dt       = T_period / 1000              # Time step: 1000 points per cycle
t        = np.arange(0, t_total, dt)    # Time array [seconds]

# ─────────────────────────────────────────────
# SECTION 3: FUNCTIONS
# ─────────────────────────────────────────────

def magnetic_flux(t, N, B0, A, omega):
    """
    Flux = N * B0 * A * cos(omega * t)
    As magnet rotates/oscillates, flux through coil varies sinusoidally.
    """
    return N * B0 * A * np.cos(omega * t)   # [Weber = Wb]


def induced_emf(t, N, B0, A, omega): #EMF = voltage generated by the changing flux
    """
    EMF = -dPhi/dt = N * B0 * A * omega * sin(omega * t)
    Lenz's law: sign means EMF opposes the change in flux.
    We take magnitude convention for power calculations.
    """
    return N * B0 * A * omega * np.sin(omega * t)   # [Volts]


def coil_current(emf, R):
    """
    I = EMF / R   (Ohm's Law)
    """
    return emf / R   # [Ampere]


def instantaneous_power(emf, R):
    """
    P = EMF^2 / R
    Power delivered to the resistive coil load.
    """
    return (emf ** 2) / R   # [Watts]


def energy_over_interval(power, dt):
    """
    E = integral of P dt  (numerical integration using trapezoidal rule)
    """
    try:
        return np.trapezoid(power, dx=dt)   # NumPy >= 2.0
    except AttributeError:
        return np.trapz(power, dx=dt)       # NumPy < 2.0

# ─────────────────────────────────────────────
# SECTION 4: COMPUTE ALL QUANTITIES
# ─────────────────────────────────────────────

flux    = magnetic_flux(t, N, B0, A, omega)
emf     = induced_emf(t, N, B0, A, omega)
current = coil_current(emf, R)
power   = instantaneous_power(emf, R)
energy  = energy_over_interval(power, dt)

# Peak values
emf_peak     = N * B0 * A * omega
current_peak = emf_peak / R
power_peak   = (emf_peak ** 2) / R
avg_power    = power_peak / 2   # Average power of sinusoidal signal = peak/2

# ─────────────────────────────────────────────
# SECTION 5: PRINT NUMERICAL RESULTS
# ─────────────────────────────────────────────

print("=" * 55)
print("  GROUP 9 — FARADAY'S LAW SIMULATION RESULTS")
print("=" * 55)
print(f"  Coil turns (N)         : {N}")
print(f"  Peak B-field (B0)      : {B0} T")
print(f"  Coil area (A)          : {A} m²")
print(f"  Frequency (f)          : {f} Hz")
print(f"  Angular freq (w)       : {omega:.2f} rad/s")
print(f"  Coil resistance (R)    : {R} Ohm")
print("-" * 55)
print(f"  Peak EMF               : {emf_peak:.4f} V")
print(f"  Peak Current           : {current_peak:.4f} A")
print(f"  Peak Power             : {power_peak:.4f} W")
print(f"  Average Power          : {avg_power:.4f} W")
print(f"  Total Energy (3 cycles): {energy:.6f} J")
print("=" * 55)

# ─────────────────────────────────────────────
# SECTION 6: PLOTS
# ─────────────────────────────────────────────

t_ms = t * 1000   # Convert time to milliseconds for readability

fig, axes = plt.subplots(3, 1, figsize=(12, 10))
fig.suptitle(
    "Group 9 - Faraday's Law & Motional EMF Simulation\n"
    f"N={N} turns | B0={B0} T | A={A} m2 | f={f} Hz | R={R} Ohm",
    fontsize=13, fontweight='bold'
)

# --- PLOT 1: Magnetic Flux ---
axes[0].plot(t_ms, flux * 1000, color='steelblue', linewidth=2)
axes[0].set_title("Magnetic Flux Through Coil Over Time")
axes[0].set_xlabel("Time [ms]")
axes[0].set_ylabel("Flux [mWb]")
axes[0].axhline(0, color='black', linewidth=0.7, linestyle='--')
axes[0].grid(True, alpha=0.4)
axes[0].fill_between(t_ms, flux * 1000, alpha=0.1, color='steelblue')
axes[0].annotate(
    f"Peak = {N*B0*A*1000:.2f} mWb",
    xy=(t_ms[250], flux[250]*1000),
    xytext=(t_ms[250]+2, flux[250]*1000 + 0.1),
    fontsize=9, color='steelblue'
)

# --- PLOT 2: Induced EMF and Current ---
ax2a = axes[1]
ax2b = ax2a.twinx()   # Second y-axis for current

l1, = ax2a.plot(t_ms, emf, color='darkorange', linewidth=2, label='EMF (V)')
l2, = ax2b.plot(t_ms, current, color='green', linewidth=2, linestyle='--', label='Current (A)')

ax2a.set_title("Induced EMF and Coil Current")
ax2a.set_xlabel("Time [ms]")
ax2a.set_ylabel("EMF [V]", color='darkorange')
ax2b.set_ylabel("Current [A]", color='green')
ax2a.axhline(0, color='black', linewidth=0.7, linestyle='--')
ax2a.grid(True, alpha=0.4)
ax2a.tick_params(axis='y', labelcolor='darkorange')
ax2b.tick_params(axis='y', labelcolor='green')
lines = [l1, l2]
ax2a.legend(lines, [l.get_label() for l in lines], loc='upper right', fontsize=9)

# --- PLOT 3: Instantaneous Power + Cumulative Energy ---
ax3a = axes[2]
ax3b = ax3a.twinx()

cumulative_energy = np.cumsum(power) * dt * 1000   # in mJ

l3, = ax3a.plot(t_ms, power * 1000, color='crimson', linewidth=2, label='Power (mW)')
l4, = ax3b.plot(t_ms, cumulative_energy, color='purple', linewidth=2,
                linestyle='-.', label='Cumulative Energy (mJ)')

ax3a.set_title("Instantaneous Power & Cumulative Energy Harvested")
ax3a.set_xlabel("Time [ms]")
ax3a.set_ylabel("Power [mW]", color='crimson')
ax3b.set_ylabel("Energy [mJ]", color='purple')
ax3a.axhline(0, color='black', linewidth=0.7, linestyle='--')
ax3a.grid(True, alpha=0.4)
ax3a.tick_params(axis='y', labelcolor='crimson')
ax3b.tick_params(axis='y', labelcolor='purple')
lines2 = [l3, l4]
ax3a.legend(lines2, [l.get_label() for l in lines2], loc='upper right', fontsize=9)

plt.tight_layout()
plt.savefig("group9_faraday_plots.png", dpi=150)
plt.show()
print("\n[Plot saved: group9_faraday_plots.png]")

# ─────────────────────────────────────────────
# SECTION 7: OPTIMIZATION PLOT — EMF vs Number of Turns
# ─────────────────────────────────────────────

N_range = np.arange(50, 501, 10)   # Vary turns from 50 to 500
emf_peak_N = N_range * B0 * A * omega
power_peak_N = (emf_peak_N ** 2) / R

fig2, ax = plt.subplots(1, 2, figsize=(12, 4))
fig2.suptitle("Optimization: Effect of Coil Turns on EMF and Power", fontsize=12, fontweight='bold')

ax[0].plot(N_range, emf_peak_N, color='darkorange', linewidth=2)
ax[0].axvline(N, color='black', linestyle='--', label=f'Current N={N}')
ax[0].set_title("Peak EMF vs Coil Turns")
ax[0].set_xlabel("Number of Turns (N)")
ax[0].set_ylabel("Peak EMF [V]")
ax[0].legend()
ax[0].grid(True, alpha=0.4)

ax[1].plot(N_range, power_peak_N * 1000, color='crimson', linewidth=2)
ax[1].axvline(N, color='black', linestyle='--', label=f'Current N={N}')
ax[1].set_title("Peak Power vs Coil Turns")
ax[1].set_xlabel("Number of Turns (N)")
ax[1].set_ylabel("Peak Power [mW]")
ax[1].legend()
ax[1].grid(True, alpha=0.4)

plt.tight_layout()
plt.savefig("group9_optimization_plot.png", dpi=150)
plt.show()
print("[Optimization plot saved: group9_optimization_plot.png]")

# ─────────────────────────────────────────────
# SECTION 8: EXPORT CSV FOR MODULE 10
# ─────────────────────────────────────────────

csv_filename = "group9_output.csv"

with open(csv_filename, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow([
        "time_s",
        "flux_Wb",
        "emf_V",
        "current_A",
        "power_W",
        "cumulative_energy_J"
    ])
    cum_e = np.cumsum(power) * dt
    for i in range(0, len(t), 5):
        writer.writerow([
            round(t[i], 8),
            round(flux[i], 8),
            round(emf[i], 6),
            round(current[i], 6),
            round(power[i], 6),
            round(cum_e[i], 8)
        ])

print(f"[CSV exported: {csv_filename}]")
print(f"  Rows written: {len(t)//5}")
print("\n[Module 10 can read group9_output.csv for EMF/power time-series]")

# ─────────────────────────────────────────────
# SECTION 9: ENERGY CONSERVATION CHECK
# ─────────────────────────────────────────────

E_theoretical = avg_power * t_total
E_simulated   = energy

print("\n--- ENERGY CONSERVATION CHECK ---")
print(f"  Theoretical energy (Pavg x T) : {E_theoretical:.6f} J")
print(f"  Simulated energy (integral P) : {E_simulated:.6f} J")
print(f"  Error                         : {abs(E_theoretical - E_simulated)/E_theoretical * 100:.4f}%")
print("  Energy conservation verified within numerical precision")